### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by raad-genies** [throw-out/puerts-unity-kit#6]
Hello!

# Platform

- Mac M2

# Issue

When I try to compile the `TsProject` I get an issue with `undici-types` not being found. If I change the `moduleResolution` to `node` it works but then the project throws an error in unity:

```puerts/xor-editor/child.cjs:2: Error: Debug Failure. Unexpected moduleResolution: Node

Error: Debug Failure. Unexpected moduleResolution: Node
    at Object.e.resolveModuleName (puerts/xor-editor/child.cjs:2:2007963)
    at fe (puerts/xor-editor/child.cjs:2:3194758)
    at S (puerts/xor-editor/child.cjs:2:3178834)
    at ne (puerts/xor-editor/child.cjs:2:3194839)
    at ze (puerts/xor-editor/child.cjs:2:3221816)
    at et (puerts/xor-editor/child.cjs:2:3224476)
    at Xt (puerts/xor-editor/child.cjs:2:3244795)
    at puerts/xor-editor/child.cjs:2:3240266
    at kt (puerts/xor-editor/child.cjs:2:3240303)
    at puerts/xor-editor/child.cjs:2:3237328
UnityEngine.Debug:LogError (object)
XOR.Logger:LogError (object,object[]) (at Assets/XOR/Runtime/Src/Logger.cs:84)
XOR.ThreadWorker:ProcessChildThreadMessages () (at Assets/XOR/Runtime/Src/Thread/ThreadWorker.cs:411)
XOR.ThreadWorker:ThreadExecuteTick (Puerts.JsEnv,bool) (at Assets/XOR/Runtime/Src/Thread/ThreadWorker.cs:306)
XOR.ThreadWorker:ThreadExecute (string,bool) (at Assets/XOR/Runtime/Src/Thread/ThreadWorker.cs:249)
XOR.ThreadWorker/<>c__DisplayClass48_0:<Run>b__0 () (at Assets/XOR/Runtime/Src/Thread/ThreadWorker.cs:101)
System.Threading.ThreadHelper:ThreadStart ()```

<img width="360" alt="Screenshot 2023-11-30 at 8 36 51 AM" src="https://github.com/throw-out/puerts-unity-kit/assets/108297275/a022a6bd-f468-40e3-bf51-bcdfed12cdf8">

**Comment by raad-genies** [comment]
Update: It seems like the issue with missing modules has to do with the path assuming its windows. See `IsSameDriver` in `PathUtils` this should handle unix platforms as well.

**Comment by raad-genies** [comment]
Update #2: In `NodeWrap` the `ExplicitValueEnum` values are `double` which fails to cast to `Int` in `RenderEnumValue` since there's no implicit conversion using `Cast<int>` 

the cast should be like this 

``` 
int[] valueOptions = nw.ExplicitValueEnum.Values
                                   .Select(value => (int)(double)value) // Unbox to double, then cast to int
                                   .ToArray();            var value = (int)node.doubleValue;
```

**Comment by raad-genies** [comment]
`Update #3`: For module finding to work, you need to add `moduleResolution:node` to compile, then remove it so that `child.cjs` doesn't fail resolution.

**Comment by raad-genies** [comment]
`Update #4`: For opening the IDE from `TsComponent` adding support to rider would be nice in `OpenFileInIDE` you can just add 

```
case "Rider":
    arguments = CodeEditor.ParseArgument(
                        "--line $(Line) --column $(Column) $(File)",
                        filepath,
                        line,
                        column
                    );
    break;

```

**Comment by raad-genies** [comment]
> > `Update #2`: In `NodeWrap` the `ExplicitValueEnum` values are `double` which fails to cast to `Int` in `RenderEnumValue` since there's no implicit conversion using `Cast<int>`
> > the cast should be like this
> > ```
> > int[] valueOptions = nw.ExplicitValueEnum.Values
> >                                    .Select(value => (int)(double)value) // Unbox to double, then cast to int
> >                                    .ToArray();            var value = (int)node.doubleValue;
> > ```
> 
> Under what circumstances will the problem occur? In general, type double should be able to express all int32 values.
> 
> 请问在什么情况下会出现问题?一般而言double类型应该能够表达所有int32的值

Regular usage, was using the samples scene.
